services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: esports
    user: ${postgres_user}
    volumes:
        - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${postgres_user}"]
      interval: 5s
      timeout: 5s
      retries: 5
  stalka: 
    build: .
    depends_on:
      postgres: 
        condition: service_healthy
    environment:
      pandascore_secret: ${pandascore_secret}
      postgres_user: ${postgres_user}
      postgres_password: ${postgres_password}
volumes:
  postgresql_data:
