// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbtypes

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID   int32
	Name string
	Slug pgtype.Text
}

type League struct {
	ID        int32
	Name      string
	Slug      pgtype.Text
	GameID    int32
	ImageLink pgtype.Text
}

type Match struct {
	ID                int32
	Name              string
	Slug              pgtype.Text
	Finished          bool
	ExpectedStartTime pgtype.Timestamp
	Team1ID           int32
	Team1Score        int32
	Team2ID           int32
	Team2Score        int32
	AmountOfGames     int32
	GameID            int32
	LeagueID          int32
	SeriesID          int32
	TournamentID      int32
}

type Series struct {
	ID       int32
	Name     string
	Slug     pgtype.Text
	GameID   int32
	LeagueID int32
}

type Team struct {
	ID        int32
	Name      string
	Slug      pgtype.Text
	Acronym   pgtype.Text
	ImageLink pgtype.Text
	GameID    int32
}

type Tournament struct {
	ID       int32
	Name     string
	Slug     pgtype.Text
	Tier     pgtype.Int4
	GameID   int32
	SerieID  int32
	LeagueID int32
}
