// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbtypes

import (
	"context"
)

type Querier interface {
	GameExist(ctx context.Context, id int32) (int64, error)
	InsertToGames(ctx context.Context, arg InsertToGamesParams) error
	InsertToLeagues(ctx context.Context, arg InsertToLeaguesParams) error
	InsertToMatches(ctx context.Context, arg InsertToMatchesParams) error
	InsertToSeries(ctx context.Context, arg InsertToSeriesParams) error
	InsertToTeams(ctx context.Context, arg InsertToTeamsParams) error
	InsertToTournaments(ctx context.Context, arg InsertToTournamentsParams) error
	LeagueExist(ctx context.Context, id int32) (int64, error)
	MatchExist(ctx context.Context, id int32) (int64, error)
	SeriesExist(ctx context.Context, id int32) (int64, error)
	TeamExist(ctx context.Context, id int32) (int64, error)
	TournamentExist(ctx context.Context, id int32) (int64, error)
}

var _ Querier = (*Queries)(nil)
