// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package pandatypes

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertToGames = `-- name: InsertToGames :exec
INSERT INTO games (id, name, slug) VALUES ($1, $2, $3)
`

type InsertToGamesParams struct {
	ID   int32
	Name string
	Slug pgtype.Text
}

func (q *Queries) InsertToGames(ctx context.Context, arg InsertToGamesParams) error {
	_, err := q.db.Exec(ctx, insertToGames, arg.ID, arg.Name, arg.Slug)
	return err
}

const insertToLeagues = `-- name: InsertToLeagues :exec
INSERT INTO leagues (id, name, slug, game_id, image_link) VALUES ($1, $2, $3, $4, $5)
`

type InsertToLeaguesParams struct {
	ID        int32
	Name      string
	Slug      pgtype.Text
	GameID    int32
	ImageLink pgtype.Text
}

func (q *Queries) InsertToLeagues(ctx context.Context, arg InsertToLeaguesParams) error {
	_, err := q.db.Exec(ctx, insertToLeagues,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.GameID,
		arg.ImageLink,
	)
	return err
}

const insertToMatches = `-- name: InsertToMatches :exec
INSERT INTO matches (id, name, slug, finished, expected_start_time, team1_id, team1_score, team2_id, team2_score, amount_of_games, game_id, league_id, series_id, tournament_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertToMatchesParams struct {
	ID                int32
	Name              string
	Slug              pgtype.Text
	Finished          bool
	ExpectedStartTime pgtype.Timestamp
	Team1ID           int32
	Team1Score        int32
	Team2ID           int32
	Team2Score        int32
	AmountOfGames     int32
	GameID            int32
	LeagueID          int32
	SeriesID          int32
	TournamentID      int32
}

func (q *Queries) InsertToMatches(ctx context.Context, arg InsertToMatchesParams) error {
	_, err := q.db.Exec(ctx, insertToMatches,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Finished,
		arg.ExpectedStartTime,
		arg.Team1ID,
		arg.Team1Score,
		arg.Team2ID,
		arg.Team2Score,
		arg.AmountOfGames,
		arg.GameID,
		arg.LeagueID,
		arg.SeriesID,
		arg.TournamentID,
	)
	return err
}

const insertToSeries = `-- name: InsertToSeries :exec
INSERT INTO series (id, name, slug, game_id, league_id) VALUES ($1, $2, $3, $4, $5)
`

type InsertToSeriesParams struct {
	ID       int32
	Name     string
	Slug     pgtype.Text
	GameID   int32
	LeagueID int32
}

func (q *Queries) InsertToSeries(ctx context.Context, arg InsertToSeriesParams) error {
	_, err := q.db.Exec(ctx, insertToSeries,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.GameID,
		arg.LeagueID,
	)
	return err
}

const insertToTeams = `-- name: InsertToTeams :exec
INSERT INTO teams (id, name, slug, acronym, image_link, game_id) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertToTeamsParams struct {
	ID        int32
	Name      string
	Slug      pgtype.Text
	Acronym   pgtype.Text
	ImageLink pgtype.Text
	GameID    int32
}

func (q *Queries) InsertToTeams(ctx context.Context, arg InsertToTeamsParams) error {
	_, err := q.db.Exec(ctx, insertToTeams,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Acronym,
		arg.ImageLink,
		arg.GameID,
	)
	return err
}

const insertToTournaments = `-- name: InsertToTournaments :exec
INSERT INTO tournaments (id,name, slug,tier, game_id, serie_id, league_id) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertToTournamentsParams struct {
	ID       int32
	Name     string
	Slug     pgtype.Text
	Tier     pgtype.Int4
	GameID   int32
	SerieID  int32
	LeagueID int32
}

func (q *Queries) InsertToTournaments(ctx context.Context, arg InsertToTournamentsParams) error {
	_, err := q.db.Exec(ctx, insertToTournaments,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Tier,
		arg.GameID,
		arg.SerieID,
		arg.LeagueID,
	)
	return err
}
